[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.2.3"
edition = "2024"
authors = ["Jun Ryu <junhsss@gmail.com>"]
description = "Syscall interception on loopback"
license = "MIT"
repository = "https://github.com/silo-rs/silo"
homepage = "https://github.com/silo-rs/silo"

[workspace.dependencies]
# silo deps
serde = { version = "1", features = ["derive"] }
toml = "0.9"
eyre = "0.6"
thiserror = "2"
colored = "3"
dirs = "6"
glob = "0.3"
which = "8"
tracing = "0.1"
fd-lock = "4"

# silo-cli deps
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# silo-bind deps
libc = "0.2"

# dev deps
tempfile = "3"

# Theㅣ profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
