[workspace]
members = ["crates/*"]
exclude = ["crates/silo-ebpf"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2024"
authors = ["Jun Ryu <junhsss@gmail.com>"]
description = "Transparent port isolation for parallel development"
license = "MIT"
repository = "https://github.com/silo-rs/silo"
homepage = "https://github.com/silo-rs/silo"

[workspace.dependencies]
# silo deps
eyre = "0.6"
thiserror = "2"
colored = "3"
dirs = "6"
which = "8"
tracing = "0.1"
fd-lock = "4"

# silo-cli deps
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# silo-bind deps
libc = "0.2"

# ebpf deps
aya = "0.13"

# dev deps
tempfile = "3"

[workspace.lints.rust]
unsafe_code = "allow"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
redundant_clone = "deny"
uninlined_format_args = "allow"

[profile.release.package.silo-bind]
opt-level = 3
codegen-units = 1

[profile.dist]
inherits = "release"
lto = "fat"
strip = true
codegen-units = 1
