[package]
name = "silo-ebpf-tests"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true }
eyre = { workspace = true }


[[bin]]
name = "ebpf-helper"
path = "src/bin/ebpf_helper.rs"
