[package]
name = "silo"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[dependencies]
thiserror = { workspace = true }
dirs = { workspace = true }
which = { workspace = true }
tracing = { workspace = true }
fd-lock = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
