[package]
name = "silo-cli"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[[bin]]
name = "silo"
path = "src/main.rs"

[dependencies]
silo = { path = "../silo" }
clap = { workspace = true }
eyre = { workspace = true }
color-eyre = { workspace = true }
colored = { workspace = true }
dirs = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true }
libc = { workspace = true }

